---
- name: default-jdk
  hosts: both
  become: yes

  tasks:
  - name: Ensure java is present
    apt:
     name: default-jdk
     state: present

- name: maven && git
  hosts: assembly
  become: yes

  tasks:
  - name: Ensure maven is present
    apt:
     name: maven
     state: present

  tasks:
  - name: Ensure maven is present
    apt:
     name: git
     state: present

- name: Clone && mvn package && fetch war file
  hosts: assembly
  become: yes
  tasks:
   - name: Clone a github repository
     git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
       dest: /home/aldav/repos/
       clone: yes
       update: yes

  tasks:
   - name: "source code : local install"
     command: mvn --batch-mode --quiet install
     args:
       chdir: "/home/aldav/repos"

  tasks:
   - name: "fetch war"
     fetch:
       src: /home/aldav/repos/target/hello-1.0.war
       dest: /home/aldav/tmp/
       flat: true	


- name: copy war file && install tomcat server
  hosts: prod
  become: true
  tasks:
   - name: Copy war file to prod 
     copy:
       src: /home/aldav/tmp/hello-1.0.war
       dest: /var/lib/tomcat9/webapps

  tasks:
  - name: Ensure tomcat is present
    apt:
     name: tomcat9
     state: present


 
