---
- name: default-jdk
  hosts: both
  become: yes

  tasks:
  - name: Ensure java is present
    apt:
     name: default-jdk
     state: present

- name: maven
  hosts: assembly
  become: yes

  tasks:
  - name: Ensure maven is present
    apt:
     name: maven
     state: present

- name: git
  hosts: assembly
  become: yes

  tasks:
  - name: Ensure maven is present
    apt:
     name: git
     state: present

- name: Clone 
  hosts: assembly
  become: yes
  tasks:
   - name: Clone a github repository
     git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
       dest: /home/aldav/repos/
       clone: yes
       update: yes


- name: mvn package
  hosts: assembly
  become: yes
  tasks:
   - name: "source code : local install"
     command: mvn --batch-mode --quiet install
     args:
       chdir: "/home/aldav/repos"

- name: fetch war file
  hosts: assembly
  become: true  
  tasks:
   - name: "fetch war"
     fetch:
       src: /home/aldav/repos/target/hello-1.0.war
       dest: /home/aldav/tmp/
       flat: true	


- name: copy war file
  hosts: prod
  become: true
  tasks:
   - name: Copy war file to prod 
     copy:
       src: /home/aldav/tmp/hello-1.0.war
       dest: /var/lib/tomcat9/webapps

- name: install tomcat server
  hosts: prod
  become: true

  tasks:
  - name: Ensure tomcat is present
    apt:
     name: tomcat9
     state: present


 
